version: "3"
services:
  gui:
    image: bnhf/openvpn-admin-plus:latest
    logging:
      driver: "json-file"
      options:
        max-size: "100k"
    environment:
      - OPENVPN_ADMIN_USERNAME=admin
      - OPENVPN_ADMIN_PASSWORD=b3secure
      - COUNTRY=${COUNTRY}
      - PROVINCE=${PROVINCE}
      - CITY=${CITY}
      - ORG=${ORG}
      - EMAIL=${EMAIL}
      - OU=${OU}
      - PIVPN_SERVER=${PIVPN_SERVER}
      - PIVPN_CONF=${PIVPN_CONF}
      - TZ=${TZ}
      - ENABLEHTTPS=${ENABLEHTTPS}
      - HTTPSPORT=${HTTPSPORT}
      - HTTPSCERT=${HTTPSCERT}
      - HTTPSKEY=${HTTPSKEY}
    ports:
      - "8080:8080/tcp"
      - "8443:8443/tcp"
    volumes:
      - vpn:/etc/openvpn
      - vpn:/opt/openvpn-gui-tap/db

volumes:
  vpn:
